[project]
name = "blindat"
version = "0.1.1"
description = "blind pandas dataframes"
readme = "README.md"
authors = [
    { name = "ad3ller", email = "13367711+ad3ller@users.noreply.github.com" }
]
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "pandas",
]
